services:
  postgres:
    image: postgres:16
    container_name: postgresTopClass
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: topClass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d topClass" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    networks:
      app_net:
        aliases:
          - postgres

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadminTopClass
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_net

  app:
    build: .
    container_name: apiAppTopClass
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/topClass
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app_net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app_net:
    driver: bridge
